DROP TABLE RESPUESTA;
DROP TABLE EVALUACION;
DROP TABLE PUNTO_EVALUACION;
DROP TABLE PLANTILLA;
DROP TABLE ESTADO_EVALUACION;
DROP TABLE USUARIO;
DROP TABLE ROL;

CREATE TABLE ROL (
    ID_ROL      int NOT NULL, 
    DESCRIPCION varchar(50) NOT NULL, 
    PRIMARY KEY (ID_ROL)
);

CREATE TABLE ESTADO_EVALUACION (
    ID_ESTADO_EVALUACION int NOT NULL, 
    DESCRIPCION          varchar(50) NOT NULL, 
    PRIMARY KEY (ID_ESTADO_EVALUACION)
);

CREATE TABLE USUARIO (
    ID_USUARIO         int NOT NULL AUTO_INCREMENT, 
    NOMBRE             varchar(100) NOT NULL, 
    NOMBRE_USUARIO     varchar(100) NOT NULL, 
    CLAVE              varchar(16) NOT NULL, 
    ID_SUPERVISOR      int, 
    ID_USUARIO_CREADOR int NOT NULL, 
    ID_ROL             int NOT NULL, 
    PRIMARY KEY (ID_USUARIO),

    FOREIGN KEY (ID_SUPERVISOR) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_USUARIO_CREADOR) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE PLANTILLA (
    ID_PLANTILLA       int NOT NULL AUTO_INCREMENT, 
    FECHA_CREADA       date NOT NULL, 
    ID_USUARIO_CREADOR int NOT NULL, 
    PRIMARY KEY (ID_PLANTILLA),

    FOREIGN KEY (ID_USUARIO_CREADOR) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE PUNTO_EVALUACION (
    ID_PUNTO_EVALUACION int NOT NULL, 
    ID_PLANTILLA        int NOT NULL, 
    DESCRIPCION         varchar(500) NOT NULL, 
    PRIMARY KEY (ID_PUNTO_EVALUACION, ID_PLANTILLA),

    FOREIGN KEY (ID_PLANTILLA) REFERENCES PLANTILLA (ID_PLANTILLA)
);
CREATE TABLE EVALUACION (
    ID_EVALUACION        int NOT NULL AUTO_INCREMENT, 
    ID_PLANTILLA         int NOT NULL, 
    FECHA_CREADA         date NOT NULL, 
    ID_SUPERVISOR        int NOT NULL, 
    ID_REPRESENTANTE     int NOT NULL, 
    ID_ESTADO_EVALUACION int NOT NULL, 
    PRIMARY KEY (ID_EVALUACION, ID_PLANTILLA),

    FOREIGN KEY (ID_SUPERVISOR) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_REPRESENTANTE) REFERENCES USUARIO (ID_USUARIO),
    FOREIGN KEY (ID_PLANTILLA) REFERENCES PLANTILLA (ID_PLANTILLA),
    FOREIGN KEY (ID_ESTADO_EVALUACION) REFERENCES ESTADO_EVALUACION (ID_ESTADO_EVALUACION)
);
CREATE TABLE RESPUESTA (
    ID_EVALUACION       int NOT NULL, 
    ID_PUNTO_EVALUACION int NOT NULL, 
    ID_PLANTILLA        int NOT NULL, 
    CUMPLE_PUNTO        int NOT NULL, 
    ES_RECLAMADA        int DEFAULT 0 NOT NULL, 
    COMENTARIO          varchar(500), 
    PRIMARY KEY (ID_EVALUACION, ID_PUNTO_EVALUACION, ID_PLANTILLA),
    FOREIGN KEY (ID_EVALUACION, ID_PLANTILLA) REFERENCES EVALUACION (ID_EVALUACION, ID_PLANTILLA),
    FOREIGN KEY (ID_PLANTILLA, ID_PUNTO_EVALUACION) REFERENCES PUNTO_EVALUACION (ID_PLANTILLA, ID_PUNTO_EVALUACION)
);

